"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CapivaraSession, capivaraAuthed, capivaraRpc, capivaraSignIn, capivaraSignUp } from "../../../lib/capivara-supabase";
import s from "./biz.module.css";

type Product={id:number;name:string;detail:string;category:string;price:number;cost:number;stock:number;min_stock:number;image:string;badge?:string|null;active:boolean;is_alcoholic:boolean;sku?:string|null;barcode?:string|null;unit?:string};
type Entry={id:number;entry_type:"income"|"expense";category:string;description:string;amount:number;entry_date:string};
type Order={id:string;code:string;customer_name:string;total:number;status:string;payment_method?:string|null;created_at:string};
type Coupon={id:number;code:string;description?:string|null;discount_type:"fixed"|"percent";discount_value:number;minimum_value:number;active:boolean};
type Settings={id:number;store_name:string;whatsapp?:string|null;free_delivery_at:number;delivery_fee:number;accent_color:string;logo_url?:string|null;hero_title?:string|null;hero_subtitle?:string|null;instagram?:string|null;address?:string|null;pix_key?:string|null};
type Tab="home"|"pdv"|"products"|"stock"|"orders"|"finance"|"coupons"|"brand";
const SESSION="capivara-admin-session-v1";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;

function readSession():CapivaraSession|null{if(typeof window==="undefined")return null;try{const r=localStorage.getItem(SESSION);return r?JSON.parse(r):null}catch{return null}}

function Access({onSession}:{onSession:(x:CapivaraSession)=>void}){
  const [signup,setSignup]=useState(false),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const email=String(f.get("email")||"");const password=String(f.get("password")||"");
    try{if(signup){const r=await capivaraSignUp(email,password);const x="access_token" in r?r:r.session;if(!x){setMsg("Conta criada. Confirme o e-mail e depois entre.");setSignup(false)}else{localStorage.setItem(SESSION,JSON.stringify(x));onSession(x)}}else{const x=await capivaraSignIn(email,password);localStorage.setItem(SESSION,JSON.stringify(x));onSession(x)}}catch(err){setMsg(err instanceof Error?err.message:"Falha no acesso")}finally{setBusy(false)}
  }
  return <main className={s.access}><section><div className={s.logo}><b>CB</b><span>capivara<small>BIZ</small></span></div><p className={s.eyebrow}>GESTÃO CAPIVARA BEER</p><h1>Controle simples para operar rápido.</h1><p className={s.sub}>Venda no balcão, estoque, catálogo e financeiro em um único lugar.</p><form onSubmit={submit}><label>E-mail<input type="email" name="email" required/></label><label>Senha<input type="password" name="password" minLength={6} required/></label>{msg&&<i>{msg}</i>}<button disabled={busy}>{busy?"Aguarde...":signup?"Criar acesso":"Entrar"}</button></form><button className={s.link} onClick={()=>setSignup(!signup)}>{signup?"Já tenho acesso":"Primeiro acesso"}</button></section><aside><span>CAPIVARA BIZ</span><strong>Venda.<br/>Controle.<br/>Cresça.</strong></aside></main>
}

function Claim({session,onOk,onOut}:{session:CapivaraSession;onOk:()=>void;onOut:()=>void}){
 const [msg,setMsg]=useState("");
 async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await capivaraRpc("claim_capivara_admin",{p_code:String(f.get("code")||"")},session.access_token);onOk()}catch(err){setMsg(err instanceof Error?err.message:"Código inválido")}}
 return <main className={s.access}><section><div className={s.logo}><b>CB</b><span>capivara<small>BIZ</small></span></div><p className={s.eyebrow}>ATIVAÇÃO</p><h1>Autorizar este administrador.</h1><p className={s.sub}>Use o código único de primeiro acesso.</p><form onSubmit={go}><label>Código de ativação<input name="code" required/></label>{msg&&<i>{msg}</i>}<button>Ativar painel</button></form><button className={s.link} onClick={onOut}>Sair</button></section><aside><span>SEGURANÇA</span><strong>Acesso<br/>protegido.</strong></aside></main>
}

export default function Biz(){
 const [session,setSession]=useState<CapivaraSession|null>(()=>readSession()),[admin,setAdmin]=useState<boolean|null>(null),[tab,setTab]=useState<Tab>("home");
 const [products,setProducts]=useState<Product[]>([]),[finance,setFinance]=useState<Entry[]>([]),[orders,setOrders]=useState<Order[]>([]),[coupons,setCoupons]=useState<Coupon[]>([]),[settings,setSettings]=useState<Settings|null>(null);
 const [productModal,setProductModal]=useState(false),[financeModal,setFinanceModal]=useState(false),[couponModal,setCouponModal]=useState(false),[editProduct,setEditProduct]=useState<Product|null>(null),[editCoupon,setEditCoupon]=useState<Coupon|null>(null);
 const [q,setQ]=useState(""),[posQ,setPosQ]=useState(""),[cart,setCart]=useState<Record<number,number>>({}),[payment,setPayment]=useState("Pix"),[customer,setCustomer]=useState(""),[toast,setToast]=useState(""),[busy,setBusy]=useState(false);
 const token=session?.access_token||"";
 const logout=useCallback(()=>{localStorage.removeItem(SESSION);setSession(null);setAdmin(null)},[]);
 const check=useCallback(async()=>{if(!session)return;try{const r=await capivaraAuthed("admin_users?select=user_id&user_id=eq."+session.user.id,session.access_token);setAdmin(Array.isArray(r)&&r.length>0)}catch{setAdmin(false)}},[session]);
 const load=useCallback(async()=>{if(!session||!admin)return;try{const r=await Promise.all([capivaraAuthed("products?select=*&order=id.asc",token),capivaraAuthed("finance_entries?select=*&order=created_at.desc&limit=200",token),capivaraAuthed("orders?select=*&order=created_at.desc&limit=200",token),capivaraAuthed("coupons?select=*&order=created_at.desc",token),capivaraAuthed("store_settings?select=*&id=eq.1",token)]);setProducts((r[0] as Product[]).map(x=>({...x,price:num(x.price),cost:num(x.cost),stock:num(x.stock),min_stock:num(x.min_stock)})));setFinance((r[1] as Entry[]).map(x=>({...x,amount:num(x.amount)})));setOrders((r[2] as Order[]).map(x=>({...x,total:num(x.total)})));setCoupons((r[3] as Coupon[]).map(x=>({...x,discount_value:num(x.discount_value),minimum_value:num(x.minimum_value)})));const st=Array.isArray(r[4])?r[4][0]:null;setSettings(st?{...st,delivery_fee:num(st.delivery_fee),free_delivery_at:num(st.free_delivery_at)}:null)}catch(err){setToast(err instanceof Error?err.message:"Erro ao carregar")}},[session,admin,token]);
 useEffect(()=>{if(session)check()},[session,check]);useEffect(()=>{if(admin)load()},[admin,load]);useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(id)},[toast]);

 const revenue=finance.filter(x=>x.entry_type==="income").reduce((a,b)=>a+b.amount,0),expenses=finance.filter(x=>x.entry_type==="expense").reduce((a,b)=>a+b.amount,0),stockCost=products.reduce((a,p)=>a+p.stock*p.cost,0),low=products.filter(p=>p.stock<=p.min_stock);
 const filtered=products.filter(p=>(p.name+" "+p.category+" "+(p.sku||"")+" "+(p.barcode||"")).toLowerCase().includes(q.toLowerCase()));
 const posProducts=products.filter(p=>p.active&&p.stock>0&&(p.name+" "+p.category+" "+(p.barcode||"")).toLowerCase().includes(posQ.toLowerCase()));
 const items=products.filter(p=>(cart[p.id]||0)>0),total=items.reduce((a,p)=>a+p.price*cart[p.id],0);
 if(!session)return <Access onSession={setSession}/>;if(admin===null)return <main className={s.loading}>Carregando Capivara Biz...</main>;if(!admin)return <Claim session={session} onOk={check} onOut={logout}/>;

 async function saveProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const body={name:String(f.get("name")||""),detail:String(f.get("detail")||""),category:String(f.get("category")||"Cervejas"),price:num(f.get("price")),cost:num(f.get("cost")),stock:Math.max(0,Math.floor(num(f.get("stock")))),min_stock:Math.max(0,Math.floor(num(f.get("min_stock")))),image:String(f.get("image")||"/capivara-beer-mascot.webp"),badge:String(f.get("badge")||"")||null,sku:String(f.get("sku")||"")||null,barcode:String(f.get("barcode")||"")||null,unit:String(f.get("unit")||"un"),active:f.get("active")==="on",is_alcoholic:f.get("is_alcoholic")==="on"};try{if(editProduct)await capivaraAuthed("products?id=eq."+editProduct.id,token,{method:"PATCH",body:JSON.stringify(body)});else await capivaraAuthed("products",token,{method:"POST",body:JSON.stringify(body)});setProductModal(false);setEditProduct(null);setToast("Produto salvo e sincronizado.");await load()}catch(err){setToast(err instanceof Error?err.message:"Erro ao salvar")}finally{setBusy(false)}}
 async function stock(p:Product,delta:number,reason:string){try{await capivaraRpc("adjust_stock",{p_product_id:p.id,p_delta:delta,p_reason:reason},token);setToast(delta>0?"Entrada registrada.":"Saída registrada.");await load()}catch(err){setToast(err instanceof Error?err.message:"Erro no estoque")}}
 async function sale(){if(!items.length)return;setBusy(true);try{const r=await capivaraRpc<{code:string;total:number}>("register_pos_sale",{p_items:items.map(p=>({product_id:p.id,quantity:cart[p.id]})),p_payment_method:payment,p_customer_name:customer||"Venda balcão"},token);setCart({});setCustomer("");setToast("Venda "+r.code+" finalizada: "+money.format(num(r.total)));await load()}catch(err){setToast(err instanceof Error?err.message:"Erro na venda")}finally{setBusy(false)}}
 async function saveFinance(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await capivaraAuthed("finance_entries",token,{method:"POST",body:JSON.stringify({entry_type:String(f.get("entry_type")),category:String(f.get("category")),description:String(f.get("description")),amount:num(f.get("amount")),entry_date:String(f.get("entry_date")),payment_method:String(f.get("payment_method")||"")})});setFinanceModal(false);setToast("Lançamento salvo.");await load()}catch(err){setToast(err instanceof Error?err.message:"Erro financeiro")}}
 async function saveCoupon(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={code:String(f.get("code")||"").toUpperCase(),description:String(f.get("description")||""),discount_type:String(f.get("discount_type")),discount_value:num(f.get("discount_value")),minimum_value:num(f.get("minimum_value")),active:f.get("active")==="on"};try{if(editCoupon)await capivaraAuthed("coupons?id=eq."+editCoupon.id,token,{method:"PATCH",body:JSON.stringify(body)});else await capivaraAuthed("coupons",token,{method:"POST",body:JSON.stringify(body)});setCouponModal(false);setEditCoupon(null);setToast("Cupom salvo.");await load()}catch(err){setToast(err instanceof Error?err.message:"Erro no cupom")}}
 async function saveBrand(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={store_name:String(f.get("store_name")),whatsapp:String(f.get("whatsapp")),accent_color:String(f.get("accent_color")),logo_url:String(f.get("logo_url")),hero_title:String(f.get("hero_title")),hero_subtitle:String(f.get("hero_subtitle")),delivery_fee:num(f.get("delivery_fee")),free_delivery_at:num(f.get("free_delivery_at")),instagram:String(f.get("instagram")),pix_key:String(f.get("pix_key")),address:String(f.get("address"))};try{await capivaraAuthed("store_settings?id=eq.1",token,{method:"PATCH",body:JSON.stringify(body)});setToast("Personalização salva.");await load()}catch(err){setToast(err instanceof Error?err.message:"Erro ao salvar")}}

 const nav:[Tab,string][]=[["home","Visão geral"],["pdv","Venda rápida"],["orders","Pedidos"],["products","Produtos"],["stock","Estoque"],["finance","Financeiro"],["coupons","Cupons"],["brand","Personalização"]];
 return <main className={s.shell}><aside className={s.sidebar}><div className={s.logo}><b>CB</b><span>capivara<small>BIZ</small></span></div><div className={s.sync}>● Loja sincronizada</div><nav>{nav.map(x=><button key={x[0]} className={tab===x[0]?s.active:""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav><div className={s.bottom}><a href="/" target="_blank">Abrir loja ↗</a><button onClick={logout}>Sair</button></div></aside><section className={s.content}><header><div><small>CAPIVARA BEER • GESTÃO</small><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1><p>{tab==="pdv"?"Venda no balcão com baixa automática de estoque.":"Dados reais do Supabase, sincronizados com a operação."}</p></div><div><button className={s.ghost} onClick={load}>Atualizar</button><button onClick={()=>{setEditProduct(null);setProductModal(true)}}>+ Novo produto</button></div></header>

 {tab==="home"&&<><div className={s.cards}><article><span>Faturamento</span><strong>{money.format(revenue)}</strong><small>Entradas registradas</small></article><article><span>Resultado líquido</span><strong>{money.format(revenue-expenses)}</strong><small>{money.format(expenses)} em saídas</small></article><article><span>Estoque a custo</span><strong>{money.format(stockCost)}</strong><small>{products.reduce((a,p)=>a+p.stock,0)} unidades</small></article><article><span>Estoque crítico</span><strong>{low.length}</strong><small>itens no mínimo ou abaixo</small></article></div><div className={s.quick}><button onClick={()=>setTab("pdv")}><b>Venda rápida</b><span>Baixa automática no estoque</span></button><button onClick={()=>setTab("stock")}><b>Ajustar estoque</b><span>Entrada e saída em um toque</span></button><button onClick={()=>setTab("products")}><b>Editar catálogo</b><span>Preço, foto, nome e disponibilidade</span></button></div><section className={s.panel}><div className={s.panelHead}><div><small>ATENÇÃO</small><h2>Estoque baixo</h2></div></div><div className={s.low}>{low.map(p=><div key={p.id}><img src={p.image} alt=""/><span><b>{p.name}</b><small>Mínimo {p.min_stock}</small></span><strong>{p.stock} un.</strong></div>)}</div></section></>}

 {tab==="pdv"&&<div className={s.pos}><section className={s.panel}><div className={s.search}><div><small>VENDA NO LOCAL</small><h2>Adicionar produtos</h2></div><input value={posQ} onChange={e=>setPosQ(e.target.value)} placeholder="Buscar produto ou código de barras"/></div><div className={s.productGrid}>{posProducts.map(p=><button key={p.id} onClick={()=>setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}))}><img src={p.image} alt=""/><span><b>{p.name}</b><small>{p.stock} em estoque</small></span><strong>{money.format(p.price)}</strong></button>)}</div></section><aside className={s.cart}><div className={s.cartTop}><b>VENDA ATUAL</b><button onClick={()=>setCart({})}>Limpar</button></div>{items.map(p=><div className={s.cartItem} key={p.id}><span><b>{p.name}</b><small>{money.format(p.price)}</small></span><div><button onClick={()=>setCart(c=>({...c,[p.id]:Math.max(0,(c[p.id]||0)-1)}))}>−</button><i>{cart[p.id]}</i><button onClick={()=>setCart(c=>({...c,[p.id]:(c[p.id]||0)+1}))}>+</button></div><strong>{money.format(p.price*cart[p.id])}</strong></div>)}{!items.length&&<p className={s.empty}>Adicione os itens vendidos.</p>}<label>Cliente <small>(opcional)</small><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Venda balcão"/></label><label>Pagamento<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Pix</option><option>Dinheiro</option><option>Cartão de crédito</option><option>Cartão de débito</option></select></label><div className={s.total}><span>Total</span><strong>{money.format(total)}</strong></div><button className={s.finish} disabled={busy||!items.length} onClick={sale}>Finalizar venda e baixar estoque</button><small className={s.hint}>A venda entra no financeiro e reduz o estoque automaticamente.</small></aside></div>}

 {tab==="products"&&<section className={s.panel}><div className={s.search}><div><small>CATÁLOGO</small><h2>{products.length} produtos</h2></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar produto, SKU ou código"/></div><div className={s.table}><div className={s.th}><span>Produto</span><span>Categoria</span><span>Preço</span><span>Estoque</span><span>Status</span><span>Ações</span></div>{filtered.map(p=><div className={s.tr} key={p.id}><span className={s.product}><img src={p.image} alt=""/><b>{p.name}<small>{p.detail}</small></b></span><span>{p.category}</span><span>{money.format(p.price)}<small>Custo {money.format(p.cost)}</small></span><span className={p.stock<=p.min_stock?s.warn:""}>{p.stock} un.</span><span>{p.active?"Publicado":"Oculto"}</span><span><button onClick={()=>{setEditProduct(p);setProductModal(true)}}>Editar</button><button className={s.red} onClick={async()=>{if(confirm("Excluir "+p.name+"?")){await capivaraAuthed("products?id=eq."+p.id,token,{method:"DELETE"});await load()}}}>Excluir</button></span></div>)}</div></section>}

 {tab==="stock"&&<section className={s.panel}><div className={s.panelHead}><div><small>ESTOQUE</small><h2>Baixa e entrada rápida</h2></div></div><div className={s.stock}>{products.map(p=><article key={p.id} className={p.stock<=p.min_stock?s.critical:""}><img src={p.image} alt=""/><div><small>{p.category}</small><h3>{p.name}</h3><p>Atual <b>{p.stock}</b> • mínimo {p.min_stock}</p></div><div><button onClick={()=>stock(p,-1,"Saída rápida")}>−1</button><button onClick={()=>stock(p,-6,"Saída de 6")}>−6</button><button onClick={()=>stock(p,1,"Entrada rápida")}>+1</button><button onClick={()=>stock(p,12,"Entrada de 12")}>+12</button><button onClick={()=>{const r=prompt("Quantidade do ajuste. Negativo = saída, positivo = entrada","1");if(r&&Number.isInteger(Number(r))&&Number(r)!==0)stock(p,Number(r),prompt("Motivo","Ajuste manual")||"Ajuste manual")}}>Ajuste livre</button></div></article>)}</div></section>}

 {tab==="orders"&&<section className={s.panel}><div className={s.panelHead}><div><small>PEDIDOS</small><h2>Histórico e status</h2></div></div><div className={s.orders}>{orders.map(o=><article key={o.id}><span><b>{o.code}</b><small>{o.customer_name}</small></span><strong>{money.format(o.total)}</strong><select value={o.status} onChange={async e=>{await capivaraAuthed("orders?id=eq."+o.id,token,{method:"PATCH",body:JSON.stringify({status:e.target.value})});await load()}}><option>Novo</option><option>Preparando</option><option>Saiu</option><option>Concluído</option><option>Cancelado</option></select></article>)}</div></section>}

 {tab==="finance"&&<><div className={s.cards}><article><span>Entradas</span><strong>{money.format(revenue)}</strong></article><article><span>Saídas</span><strong>{money.format(expenses)}</strong></article><article><span>Saldo</span><strong>{money.format(revenue-expenses)}</strong></article><article><span>Estoque a custo</span><strong>{money.format(stockCost)}</strong></article></div><section className={s.panel}><div className={s.panelHead}><div><small>FINANCEIRO</small><h2>Lançamentos</h2></div><button onClick={()=>setFinanceModal(true)}>+ Lançamento</button></div><div className={s.entries}>{finance.map(f=><div key={f.id}><i className={f.entry_type==="income"?s.plus:s.minus}>{f.entry_type==="income"?"+":"−"}</i><span><b>{f.description}</b><small>{f.category} • {f.entry_date}</small></span><strong>{f.entry_type==="income"?"+ ":"− "}{money.format(f.amount)}</strong></div>)}</div></section></>}

 {tab==="coupons"&&<section className={s.panel}><div className={s.panelHead}><div><small>PROMOÇÕES</small><h2>Cupons</h2></div><button onClick={()=>{setEditCoupon(null);setCouponModal(true)}}>+ Novo cupom</button></div><div className={s.coupons}>{coupons.map(c=><article key={c.id}><span>{c.active?"ATIVO":"PAUSADO"}</span><h3>{c.code}</h3><p>{c.description}</p><strong>{c.discount_type==="percent"?String(c.discount_value)+"%":money.format(c.discount_value)}</strong><small>Mínimo {money.format(c.minimum_value)}</small><button onClick={()=>{setEditCoupon(c);setCouponModal(true)}}>Editar</button></article>)}</div></section>}

 {tab==="brand"&&settings&&<section className={s.panel}><div className={s.panelHead}><div><small>CAPIVARA BIZ</small><h2>Personalização da loja</h2></div></div><form className={s.brandForm} onSubmit={saveBrand}><aside><img src={settings.logo_url||"/capivara-beer-logo.webp"} alt=""/><span style={{background:settings.accent_color||"#9BCF2F"}}/><h3>{settings.store_name}</h3><p>{settings.hero_title}</p></aside><div><label>Nome da loja<input name="store_name" defaultValue={settings.store_name}/></label><label>WhatsApp<input name="whatsapp" defaultValue={settings.whatsapp||""}/></label><label>Cor principal<input name="accent_color" type="color" defaultValue={settings.accent_color||"#9BCF2F"}/></label><label>Logo<input name="logo_url" defaultValue={settings.logo_url||""}/></label><label className={s.wide}>Título<input name="hero_title" defaultValue={settings.hero_title||""}/></label><label className={s.wide}>Subtítulo<textarea name="hero_subtitle" defaultValue={settings.hero_subtitle||""}/></label><label>Taxa de entrega<input name="delivery_fee" type="number" step=".01" defaultValue={settings.delivery_fee}/></label><label>Entrega grátis a partir<input name="free_delivery_at" type="number" step=".01" defaultValue={settings.free_delivery_at}/></label><label>Instagram<input name="instagram" defaultValue={settings.instagram||""}/></label><label>Chave Pix<input name="pix_key" defaultValue={settings.pix_key||""}/></label><label className={s.wide}>Endereço<input name="address" defaultValue={settings.address||""}/></label><button className={s.wide}>Salvar personalização</button></div></form></section>}
 </section>

 {productModal&&<div className={s.backdrop} onMouseDown={()=>setProductModal(false)}><form className={s.modal} onSubmit={saveProduct} onMouseDown={e=>e.stopPropagation()}><div className={s.modalHead}><div><small>CATÁLOGO</small><h2>{editProduct?"Editar produto":"Novo produto"}</h2></div><button type="button" onClick={()=>setProductModal(false)}>×</button></div><div className={s.form}><label className={s.wide}>Nome<input name="name" required defaultValue={editProduct?.name}/></label><label className={s.wide}>Descrição<input name="detail" required defaultValue={editProduct?.detail}/></label><label>Categoria<select name="category" defaultValue={editProduct?.category||"Cervejas"}><option>Cervejas</option><option>Refrigerantes</option><option>Gelo</option><option>Energéticos</option><option>Petiscos</option></select></label><label>Unidade<select name="unit" defaultValue={editProduct?.unit||"un"}><option value="un">Unidade</option><option value="cx">Caixa</option><option value="pct">Pacote</option></select></label><label>Preço<input name="price" type="number" step=".01" required defaultValue={editProduct?.price}/></label><label>Custo<input name="cost" type="number" step=".01" required defaultValue={editProduct?.cost}/></label><label>Estoque<input name="stock" type="number" required defaultValue={editProduct?.stock||0}/></label><label>Estoque mínimo<input name="min_stock" type="number" required defaultValue={editProduct?.min_stock||5}/></label><label>SKU<input name="sku" defaultValue={editProduct?.sku||""}/></label><label>Código de barras<input name="barcode" defaultValue={editProduct?.barcode||""}/></label><label>Badge<input name="badge" defaultValue={editProduct?.badge||""}/></label><label className={s.wide}>Imagem<input name="image" defaultValue={editProduct?.image||""}/></label></div><div className={s.checks}><label><input type="checkbox" name="active" defaultChecked={editProduct?.active??true}/> Publicado</label><label><input type="checkbox" name="is_alcoholic" defaultChecked={editProduct?.is_alcoholic}/> Alcoólico 18+</label></div><button className={s.save} disabled={busy}>Salvar produto</button></form></div>}

 {financeModal&&<div className={s.backdrop} onMouseDown={()=>setFinanceModal(false)}><form className={s.modal} onSubmit={saveFinance} onMouseDown={e=>e.stopPropagation()}><div className={s.modalHead}><h2>Novo lançamento</h2><button type="button" onClick={()=>setFinanceModal(false)}>×</button></div><div className={s.form}><label>Tipo<select name="entry_type"><option value="income">Entrada</option><option value="expense">Saída</option></select></label><label>Categoria<input name="category" required/></label><label className={s.wide}>Descrição<input name="description" required/></label><label>Valor<input name="amount" type="number" step=".01" required/></label><label>Data<input name="entry_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Pagamento<select name="payment_method"><option>Pix</option><option>Dinheiro</option><option>Cartão</option><option>Outro</option></select></label></div><button className={s.save}>Salvar</button></form></div>}

 {couponModal&&<div className={s.backdrop} onMouseDown={()=>setCouponModal(false)}><form className={s.modal} onSubmit={saveCoupon} onMouseDown={e=>e.stopPropagation()}><div className={s.modalHead}><h2>{editCoupon?"Editar cupom":"Novo cupom"}</h2><button type="button" onClick={()=>setCouponModal(false)}>×</button></div><div className={s.form}><label>Código<input name="code" required defaultValue={editCoupon?.code}/></label><label>Tipo<select name="discount_type" defaultValue={editCoupon?.discount_type||"fixed"}><option value="fixed">Valor fixo</option><option value="percent">Percentual</option></select></label><label>Desconto<input name="discount_value" type="number" step=".01" defaultValue={editCoupon?.discount_value}/></label><label>Compra mínima<input name="minimum_value" type="number" step=".01" defaultValue={editCoupon?.minimum_value||0}/></label><label className={s.wide}>Descrição<input name="description" defaultValue={editCoupon?.description||""}/></label></div><div className={s.checks}><label><input type="checkbox" name="active" defaultChecked={editCoupon?.active??true}/> Ativo</label></div><button className={s.save}>Salvar cupom</button></form></div>}
 {toast&&<div className={s.toast}>{toast}</div>}</main>
}